export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const BRAND_GENERATE_SUCCESS = "BRAND_GENERATE_SUCCESS";
export const BRAND_GENERATE_FAIL = "BRAND_GENERATE_FAIL";
export const REMOVE_BRAND = "REMOVE_BRAND";
export const BRAND_REQUEST = "BRAND_REQUEST";
export const BRAND_FAIL = "BRAND_FAIL";