export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CATEGORY_GENERATE_SUCCESS = "CATEGORY_GENERATE_SUCCESS";
export const CATEGORY_GENERATE_FAIL = "CATEGORY_GENERATE_FAIL";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_FAIL = "CATEGORY_FAIL";