export const GET_ALL_COUPON = "GET_ALL_COUPON";
export const COUPON_GENERATE_SUCCESS = "COUPON_GENERATE_SUCCESS";
export const COUPON_GENERATE_FAIL = "COUPON_GENERATE_FAIL";
export const REMOVE_COUPON = "REMOVE_COUPON";
export const COUPON_REQUEST = "COUPON_REQUEST";
export const COUPON_FAIL = "COUPON_FAIL";