export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY";
export const SUBCATEGORY_GENERATE_SUCCESS = "SUBCATEGORY_GENERATE_SUCCESS";
export const SUBCATEGORY_GENERATE_FAIL = "SUBCATEGORY_GENERATE_FAIL";
export const REMOVE_SUBCATEGORY = "REMOVE_SUBCATEGORY";
export const SUBCATEGORY_REQUEST = "SUBCATEGORY_REQUEST";
export const SUBCATEGORY_FAIL = "SUBCATEGORY_FAIL";